# Generated by Django 4.2.7 on 2025-11-22 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('completed', models.BooleanField(default=False)),
                ('year', models.IntegerField(help_text='Year (e.g., 2025)')),
                ('category', models.CharField(choices=[('career', 'Career'), ('health', 'Health'), ('financial', 'Financial'), ('personal', 'Personal'), ('education', 'Education'), ('relationships', 'Relationships')], default='personal', max_length=20)),
                ('quarter', models.CharField(blank=True, choices=[('Q1', 'Q1 (Jan-Mar)'), ('Q2', 'Q2 (Apr-Jun)'), ('Q3', 'Q3 (Jul-Sep)'), ('Q4', 'Q4 (Oct-Dec)')], help_text='Optional quarter assignment', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', 'category', '-created_at'],
                'indexes': [models.Index(fields=['user', 'year', 'category'], name='tasks_yearl_user_id_2dc162_idx')],
                'unique_together': {('user', 'title', 'year')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('completed', models.BooleanField(default=False)),
                ('week_start_date', models.DateField(help_text='Monday of the week (ISO week start)')),
                ('tab', models.CharField(choices=[('personal', 'Personal'), ('work', 'Work')], default='personal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start_date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'week_start_date', 'tab'], name='tasks_weekl_user_id_93ee9e_idx')],
                'unique_together': {('user', 'title', 'week_start_date', 'tab')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('completed', models.BooleanField(default=False)),
                ('month', models.IntegerField(help_text='Month number (1-12)')),
                ('year', models.IntegerField(help_text='Year (e.g., 2025)')),
                ('tab', models.CharField(choices=[('personal', 'Personal'), ('work', 'Work')], default='personal', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', '-created_at'],
                'indexes': [models.Index(fields=['user', 'year', 'month', 'tab'], name='tasks_month_user_id_8d77ba_idx')],
                'unique_together': {('user', 'title', 'month', 'year', 'tab')},
            },
        ),
    ]
