# Generated by Django 4.2.7 on 2025-11-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_yearlytask_weeklytask_monthlytask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yearlytask',
            options={'ordering': ['-year', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='yearlytask',
            name='tasks_yearl_user_id_2dc162_idx',
        ),
        migrations.RemoveField(
            model_name='yearlytask',
            name='category',
        ),
        migrations.AddIndex(
            model_name='yearlytask',
            index=models.Index(fields=['user', 'year'], name='tasks_yearl_user_id_43ceb9_idx'),
        ),
    ]
